<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitDrupal8
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
        '952683d815ff0a7bf322b93c0be7e4e4' => __DIR__ . '/..' . '/chi-teck/drupal-code-generator/src/bootstrap.php',
        '801c31d8ed748cfa537fa45402288c95' => __DIR__ . '/..' . '/psy/psysh/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'X' => 
        array (
            'XdgBaseDir\\' => 11,
        ),
        'W' => 
        array (
            'Wikimedia\\Composer\\' => 19,
            'Webmozart\\PathUtil\\' => 19,
            'Webmozart\\Assert\\' => 17,
        ),
        'T' => 
        array (
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Component\\Yaml\\' => 23,
            'Symfony\\Component\\VarDumper\\' => 28,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\Filesystem\\' => 29,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'Symfony\\Component\\Debug\\' => 24,
            'Symfony\\Component\\Console\\' => 26,
            'SelfUpdate\\' => 11,
        ),
        'R' => 
        array (
            'Robo\\' => 5,
        ),
        'P' => 
        array (
            'Psy\\' => 4,
            'Psr\\Log\\' => 8,
            'Psr\\Container\\' => 14,
            'PhpParser\\' => 10,
        ),
        'L' => 
        array (
            'League\\Container\\' => 17,
        ),
        'J' => 
        array (
            'JakubOnderka\\PhpConsoleHighlighter\\' => 35,
            'JakubOnderka\\PhpConsoleColor\\' => 29,
        ),
        'I' => 
        array (
            'Interop\\Container\\' => 18,
        ),
        'G' => 
        array (
            'Grasmash\\YamlExpander\\' => 22,
            'Grasmash\\Expander\\' => 18,
        ),
        'D' => 
        array (
            'Drush\\Internal\\' => 15,
            'Drush\\' => 6,
            'Drupal\\Driver\\' => 14,
            'Drupal\\Core\\Composer\\' => 21,
            'Drupal\\Core\\' => 12,
            'Drupal\\Component\\Version\\' => 25,
            'Drupal\\Component\\Uuid\\' => 22,
            'Drupal\\Component\\Utility\\' => 25,
            'Drupal\\Component\\Transliteration\\' => 33,
            'Drupal\\Component\\Serialization\\' => 31,
            'Drupal\\Component\\Render\\' => 24,
            'Drupal\\Component\\ProxyBuilder\\' => 30,
            'Drupal\\Component\\Plugin\\' => 24,
            'Drupal\\Component\\PhpStorage\\' => 28,
            'Drupal\\Component\\HttpFoundation\\' => 32,
            'Drupal\\Component\\Graph\\' => 23,
            'Drupal\\Component\\Gettext\\' => 25,
            'Drupal\\Component\\FileSystem\\' => 28,
            'Drupal\\Component\\FileCache\\' => 27,
            'Drupal\\Component\\EventDispatcher\\' => 33,
            'Drupal\\Component\\Discovery\\' => 27,
            'Drupal\\Component\\Diff\\' => 22,
            'Drupal\\Component\\DependencyInjection\\' => 37,
            'Drupal\\Component\\Datetime\\' => 26,
            'Drupal\\Component\\ClassFinder\\' => 29,
            'Drupal\\Component\\Bridge\\' => 24,
            'Drupal\\Component\\Assertion\\' => 27,
            'Drupal\\Component\\Annotation\\' => 28,
            'Drupal\\Component\\' => 17,
            'DrupalCodeGenerator\\' => 20,
        ),
        'C' => 
        array (
            'Consolidation\\SiteProcess\\' => 26,
            'Consolidation\\SiteAlias\\' => 24,
            'Consolidation\\OutputFormatters\\' => 31,
            'Consolidation\\Log\\' => 18,
            'Consolidation\\Filter\\' => 21,
            'Consolidation\\Config\\' => 21,
            'Consolidation\\AnnotatedCommand\\' => 31,
            'Composer\\Semver\\' => 16,
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'XdgBaseDir\\' => 
        array (
            0 => __DIR__ . '/..' . '/dnoegel/php-xdg-base-dir/src',
        ),
        'Wikimedia\\Composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/wikimedia/composer-merge-plugin/src',
        ),
        'Webmozart\\PathUtil\\' => 
        array (
            0 => __DIR__ . '/..' . '/webmozart/path-util/src',
        ),
        'Webmozart\\Assert\\' => 
        array (
            0 => __DIR__ . '/..' . '/webmozart/assert/src',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/debug',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'SelfUpdate\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/self-update/src',
        ),
        'Robo\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/robo/src',
        ),
        'Psy\\' => 
        array (
            0 => __DIR__ . '/..' . '/psy/psysh/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'League\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/container/src',
        ),
        'JakubOnderka\\PhpConsoleHighlighter\\' => 
        array (
            0 => __DIR__ . '/..' . '/jakub-onderka/php-console-highlighter/src',
        ),
        'JakubOnderka\\PhpConsoleColor\\' => 
        array (
            0 => __DIR__ . '/..' . '/jakub-onderka/php-console-color/src',
        ),
        'Interop\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/container-interop/container-interop/src/Interop/Container',
        ),
        'Grasmash\\YamlExpander\\' => 
        array (
            0 => __DIR__ . '/..' . '/grasmash/yaml-expander/src',
        ),
        'Grasmash\\Expander\\' => 
        array (
            0 => __DIR__ . '/..' . '/grasmash/expander/src',
        ),
        'Drush\\Internal\\' => 
        array (
            0 => __DIR__ . '/..' . '/drush/drush/src/internal-forks',
        ),
        'Drush\\' => 
        array (
            0 => __DIR__ . '/..' . '/drush/drush/src',
        ),
        'Drupal\\Driver\\' => 
        array (
            0 => __DIR__ . '/../..' . '/drivers/lib/Drupal/Driver',
        ),
        'Drupal\\Core\\Composer\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Core/Composer',
        ),
        'Drupal\\Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Core',
        ),
        'Drupal\\Component\\Version\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Version',
        ),
        'Drupal\\Component\\Uuid\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Uuid',
        ),
        'Drupal\\Component\\Utility\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Utility',
        ),
        'Drupal\\Component\\Transliteration\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Transliteration',
        ),
        'Drupal\\Component\\Serialization\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Serialization',
        ),
        'Drupal\\Component\\Render\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Render',
        ),
        'Drupal\\Component\\ProxyBuilder\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/ProxyBuilder',
        ),
        'Drupal\\Component\\Plugin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Plugin',
        ),
        'Drupal\\Component\\PhpStorage\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/PhpStorage',
        ),
        'Drupal\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/HttpFoundation',
        ),
        'Drupal\\Component\\Graph\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Graph',
        ),
        'Drupal\\Component\\Gettext\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Gettext',
        ),
        'Drupal\\Component\\FileSystem\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/FileSystem',
        ),
        'Drupal\\Component\\FileCache\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/FileCache',
        ),
        'Drupal\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/EventDispatcher',
        ),
        'Drupal\\Component\\Discovery\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Discovery',
        ),
        'Drupal\\Component\\Diff\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Diff',
        ),
        'Drupal\\Component\\DependencyInjection\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/DependencyInjection',
        ),
        'Drupal\\Component\\Datetime\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Datetime',
        ),
        'Drupal\\Component\\ClassFinder\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/ClassFinder',
        ),
        'Drupal\\Component\\Bridge\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Bridge',
        ),
        'Drupal\\Component\\Assertion\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Assertion',
        ),
        'Drupal\\Component\\Annotation\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Annotation',
        ),
        'Drupal\\Component\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core/lib/Drupal/Component',
        ),
        'DrupalCodeGenerator\\' => 
        array (
            0 => __DIR__ . '/..' . '/chi-teck/drupal-code-generator/src',
        ),
        'Consolidation\\SiteProcess\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/site-process/src',
        ),
        'Consolidation\\SiteAlias\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/site-alias/src',
        ),
        'Consolidation\\OutputFormatters\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/output-formatters/src',
        ),
        'Consolidation\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/log/src',
        ),
        'Consolidation\\Filter\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/filter-via-dot-access-data/src',
        ),
        'Consolidation\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/config/src',
        ),
        'Consolidation\\AnnotatedCommand\\' => 
        array (
            0 => __DIR__ . '/..' . '/consolidation/annotated-command/src',
        ),
        'Composer\\Semver\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/semver/src',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'D' => 
        array (
            'Dflydev\\DotAccessData' => 
            array (
                0 => __DIR__ . '/..' . '/dflydev/dot-access-data/src',
            ),
        ),
    );

    public static $classMap = array (
        'Drupal' => __DIR__ . '/../..' . '/core/lib/Drupal.php',
        'DrupalFinder\\DrupalFinder' => __DIR__ . '/..' . '/webflo/drupal-finder/src/DrupalFinder.php',
        'Drupal\\Component\\Utility\\Timer' => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Utility/Timer.php',
        'Drupal\\Component\\Utility\\Unicode' => __DIR__ . '/../..' . '/core/lib/Drupal/Component/Utility/Unicode.php',
        'Drupal\\Core\\Database\\Database' => __DIR__ . '/../..' . '/core/lib/Drupal/Core/Database/Database.php',
        'Drupal\\Core\\DrupalKernel' => __DIR__ . '/../..' . '/core/lib/Drupal/Core/DrupalKernel.php',
        'Drupal\\Core\\DrupalKernelInterface' => __DIR__ . '/../..' . '/core/lib/Drupal/Core/DrupalKernelInterface.php',
        'Drupal\\Core\\Site\\Settings' => __DIR__ . '/../..' . '/core/lib/Drupal/Core/Site/Settings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitDrupal8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitDrupal8::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitDrupal8::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitDrupal8::$classMap;

        }, null, ClassLoader::class);
    }
}
